-- Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2020.2 (win64) Build 3064766 Wed Nov 18 09:12:45 MST 2020
-- Date        : Sat Jul 30 13:59:53 2022
-- Host        : DESKTOP-5LLJN45 running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ BD_SEL_AXI_IN_0_0_sim_netlist.vhdl
-- Design      : BD_SEL_AXI_IN_0_0
-- Purpose     : This VHDL netlist is a functional simulation representation of the design and should not be modified or
--               synthesized. This netlist cannot be used for SDF annotated simulation.
-- Device      : xc7z020clg400-1
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
library UNISIM;
use UNISIM.VCOMPONENTS.ALL;
entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  port (
    axi_in_aclk : in STD_LOGIC;
    axi_in_aresetn : in STD_LOGIC;
    axi_in_tready : out STD_LOGIC;
    axi_in_tdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_in_tstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    axi_in_tlast : in STD_LOGIC;
    axi_in_tvalid : in STD_LOGIC;
    axi_out1_aclk : in STD_LOGIC;
    axi_out1_aresetn : in STD_LOGIC;
    axi_out1_tvalid : out STD_LOGIC;
    axi_out1_tdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_out1_tstrb : out STD_LOGIC_VECTOR ( 3 downto 0 );
    axi_out1_tlast : out STD_LOGIC;
    axi_out1_tready : in STD_LOGIC;
    axi_out2_aclk : in STD_LOGIC;
    axi_out2_aresetn : in STD_LOGIC;
    axi_out2_tvalid : out STD_LOGIC;
    axi_out2_tdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_out2_tstrb : out STD_LOGIC_VECTOR ( 3 downto 0 );
    axi_out2_tlast : out STD_LOGIC;
    axi_out2_tready : in STD_LOGIC;
    axi_out3_aclk : in STD_LOGIC;
    axi_out3_aresetn : in STD_LOGIC;
    axi_out3_tvalid : out STD_LOGIC;
    axi_out3_tdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    axi_out3_tstrb : out STD_LOGIC_VECTOR ( 3 downto 0 );
    axi_out3_tlast : out STD_LOGIC;
    axi_out3_tready : in STD_LOGIC
  );
  attribute NotValidForBitStream : boolean;
  attribute NotValidForBitStream of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is true;
  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "BD_SEL_AXI_IN_0_0,SEL_AXI_IN_v1_0,{}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "SEL_AXI_IN_v1_0,Vivado 2020.2";
end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture STRUCTURE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  signal \<const0>\ : STD_LOGIC;
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of axi_in_aclk : signal is "xilinx.com:signal:clock:1.0 AXI_IN_CLK CLK, xilinx.com:signal:clock:1.0 axi_in_aclk CLK";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of axi_in_aclk : signal is "XIL_INTERFACENAME AXI_IN_CLK, ASSOCIATED_BUSIF AXI_IN, ASSOCIATED_RESET axi_in_aresetn, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.000, INSERT_VIP 0, XIL_INTERFACENAME axi_in_aclk, ASSOCIATED_RESET axi_in_aresetn, FREQ_HZ 1e+08, FREQ_TOLERANCE_HZ 0, PHASE 0.000, CLK_DOMAIN BD_processing_system7_0_0_FCLK_CLK0, ASSOCIATED_BUSIF AXI_IN, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of axi_in_aresetn : signal is "xilinx.com:signal:reset:1.0 AXI_IN_RST RST, xilinx.com:signal:reset:1.0 axi_in_aresetn RST";
  attribute X_INTERFACE_PARAMETER of axi_in_aresetn : signal is "XIL_INTERFACENAME AXI_IN_RST, POLARITY ACTIVE_LOW, INSERT_VIP 0, XIL_INTERFACENAME axi_in_aresetn, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of axi_in_tlast : signal is "xilinx.com:interface:axis:1.0 AXI_IN TLAST";
  attribute X_INTERFACE_INFO of axi_in_tready : signal is "xilinx.com:interface:axis:1.0 AXI_IN TREADY";
  attribute X_INTERFACE_INFO of axi_in_tvalid : signal is "xilinx.com:interface:axis:1.0 AXI_IN TVALID";
  attribute X_INTERFACE_PARAMETER of axi_in_tvalid : signal is "XIL_INTERFACENAME AXI_IN, WIZ_DATA_WIDTH 32, TDATA_NUM_BYTES 4, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 1, HAS_TKEEP 0, HAS_TLAST 1, FREQ_HZ 1e+08, PHASE 0.000, CLK_DOMAIN BD_processing_system7_0_0_FCLK_CLK0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of axi_out1_aclk : signal is "xilinx.com:signal:clock:1.0 axi_out1_aclk CLK";
  attribute X_INTERFACE_PARAMETER of axi_out1_aclk : signal is "XIL_INTERFACENAME axi_out1_aclk, ASSOCIATED_RESET axi_out1_aresetn, FREQ_HZ 1e+08, FREQ_TOLERANCE_HZ 0, PHASE 0.000, CLK_DOMAIN BD_processing_system7_0_0_FCLK_CLK0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of axi_out1_aresetn : signal is "xilinx.com:signal:reset:1.0 AXI_OUT1_RST RST, xilinx.com:signal:clock:1.0 AXI_OUT1_CLK CLK, xilinx.com:signal:reset:1.0 axi_out1_aresetn RST";
  attribute X_INTERFACE_PARAMETER of axi_out1_aresetn : signal is "XIL_INTERFACENAME AXI_OUT1_RST, POLARITY ACTIVE_LOW, INSERT_VIP 0, XIL_INTERFACENAME AXI_OUT1_CLK, ASSOCIATED_BUSIF AXI_OUT1, ASSOCIATED_RESET axi_out1_aresetn, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.000, INSERT_VIP 0, XIL_INTERFACENAME axi_out1_aresetn, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of axi_out1_tlast : signal is "xilinx.com:interface:axis:1.0 AXI_OUT1 TLAST";
  attribute X_INTERFACE_INFO of axi_out1_tready : signal is "xilinx.com:interface:axis:1.0 AXI_OUT1 TREADY";
  attribute X_INTERFACE_PARAMETER of axi_out1_tready : signal is "XIL_INTERFACENAME AXI_OUT1, WIZ_DATA_WIDTH 32, TDATA_NUM_BYTES 4, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 1, HAS_TKEEP 0, HAS_TLAST 1, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of axi_out1_tvalid : signal is "xilinx.com:interface:axis:1.0 AXI_OUT1 TVALID";
  attribute X_INTERFACE_INFO of axi_out2_aclk : signal is "xilinx.com:signal:clock:1.0 AXI_OUT2_CLK CLK, xilinx.com:signal:clock:1.0 axi_out2_aclk CLK";
  attribute X_INTERFACE_PARAMETER of axi_out2_aclk : signal is "XIL_INTERFACENAME AXI_OUT2_CLK, ASSOCIATED_BUSIF AXI_OUT2, ASSOCIATED_RESET axi_out2_aresetn, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.000, INSERT_VIP 0, XIL_INTERFACENAME axi_out2_aclk, ASSOCIATED_RESET axi_out2_aresetn, FREQ_HZ 1e+08, FREQ_TOLERANCE_HZ 0, PHASE 0.000, CLK_DOMAIN BD_processing_system7_0_0_FCLK_CLK0, ASSOCIATED_BUSIF AXI_OUT2, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of axi_out2_aresetn : signal is "xilinx.com:signal:reset:1.0 AXI_OUT2_RST RST, xilinx.com:signal:reset:1.0 axi_out2_aresetn RST";
  attribute X_INTERFACE_PARAMETER of axi_out2_aresetn : signal is "XIL_INTERFACENAME AXI_OUT2_RST, POLARITY ACTIVE_LOW, INSERT_VIP 0, XIL_INTERFACENAME axi_out2_aresetn, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of axi_out2_tlast : signal is "xilinx.com:interface:axis:1.0 AXI_OUT2 TLAST";
  attribute X_INTERFACE_INFO of axi_out2_tready : signal is "xilinx.com:interface:axis:1.0 AXI_OUT2 TREADY";
  attribute X_INTERFACE_PARAMETER of axi_out2_tready : signal is "XIL_INTERFACENAME AXI_OUT2, WIZ_DATA_WIDTH 32, TDATA_NUM_BYTES 4, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 1, HAS_TKEEP 0, HAS_TLAST 1, FREQ_HZ 1e+08, PHASE 0.000, CLK_DOMAIN BD_processing_system7_0_0_FCLK_CLK0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of axi_out2_tvalid : signal is "xilinx.com:interface:axis:1.0 AXI_OUT2 TVALID";
  attribute X_INTERFACE_INFO of axi_out3_aclk : signal is "xilinx.com:signal:clock:1.0 AXI_OUT3_CLK CLK, xilinx.com:signal:clock:1.0 axi_out3_aclk CLK";
  attribute X_INTERFACE_PARAMETER of axi_out3_aclk : signal is "XIL_INTERFACENAME AXI_OUT3_CLK, ASSOCIATED_BUSIF AXI_OUT3, ASSOCIATED_RESET axi_out3_aresetn, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.000, INSERT_VIP 0, XIL_INTERFACENAME axi_out3_aclk, ASSOCIATED_RESET axi_out3_aresetn, FREQ_HZ 1e+08, FREQ_TOLERANCE_HZ 0, PHASE 0.000, CLK_DOMAIN BD_processing_system7_0_0_FCLK_CLK0, ASSOCIATED_BUSIF AXI_OUT3, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of axi_out3_aresetn : signal is "xilinx.com:signal:reset:1.0 AXI_OUT3_RST RST, xilinx.com:signal:reset:1.0 axi_out3_aresetn RST";
  attribute X_INTERFACE_PARAMETER of axi_out3_aresetn : signal is "XIL_INTERFACENAME AXI_OUT3_RST, POLARITY ACTIVE_LOW, INSERT_VIP 0, XIL_INTERFACENAME axi_out3_aresetn, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of axi_out3_tlast : signal is "xilinx.com:interface:axis:1.0 AXI_OUT3 TLAST";
  attribute X_INTERFACE_INFO of axi_out3_tready : signal is "xilinx.com:interface:axis:1.0 AXI_OUT3 TREADY";
  attribute X_INTERFACE_PARAMETER of axi_out3_tready : signal is "XIL_INTERFACENAME AXI_OUT3, WIZ_DATA_WIDTH 32, TDATA_NUM_BYTES 4, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 1, HAS_TKEEP 0, HAS_TLAST 1, FREQ_HZ 1e+08, PHASE 0.000, CLK_DOMAIN BD_processing_system7_0_0_FCLK_CLK0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of axi_out3_tvalid : signal is "xilinx.com:interface:axis:1.0 AXI_OUT3 TVALID";
  attribute X_INTERFACE_INFO of axi_in_tdata : signal is "xilinx.com:interface:axis:1.0 AXI_IN TDATA";
  attribute X_INTERFACE_INFO of axi_in_tstrb : signal is "xilinx.com:interface:axis:1.0 AXI_IN TSTRB";
  attribute X_INTERFACE_INFO of axi_out1_tdata : signal is "xilinx.com:interface:axis:1.0 AXI_OUT1 TDATA";
  attribute X_INTERFACE_INFO of axi_out1_tstrb : signal is "xilinx.com:interface:axis:1.0 AXI_OUT1 TSTRB";
  attribute X_INTERFACE_INFO of axi_out2_tdata : signal is "xilinx.com:interface:axis:1.0 AXI_OUT2 TDATA";
  attribute X_INTERFACE_INFO of axi_out2_tstrb : signal is "xilinx.com:interface:axis:1.0 AXI_OUT2 TSTRB";
  attribute X_INTERFACE_INFO of axi_out3_tdata : signal is "xilinx.com:interface:axis:1.0 AXI_OUT3 TDATA";
  attribute X_INTERFACE_INFO of axi_out3_tstrb : signal is "xilinx.com:interface:axis:1.0 AXI_OUT3 TSTRB";
begin
  axi_in_tready <= \<const0>\;
  axi_out1_tdata(31) <= \<const0>\;
  axi_out1_tdata(30) <= \<const0>\;
  axi_out1_tdata(29) <= \<const0>\;
  axi_out1_tdata(28) <= \<const0>\;
  axi_out1_tdata(27) <= \<const0>\;
  axi_out1_tdata(26) <= \<const0>\;
  axi_out1_tdata(25) <= \<const0>\;
  axi_out1_tdata(24) <= \<const0>\;
  axi_out1_tdata(23) <= \<const0>\;
  axi_out1_tdata(22) <= \<const0>\;
  axi_out1_tdata(21) <= \<const0>\;
  axi_out1_tdata(20) <= \<const0>\;
  axi_out1_tdata(19) <= \<const0>\;
  axi_out1_tdata(18) <= \<const0>\;
  axi_out1_tdata(17) <= \<const0>\;
  axi_out1_tdata(16) <= \<const0>\;
  axi_out1_tdata(15) <= \<const0>\;
  axi_out1_tdata(14) <= \<const0>\;
  axi_out1_tdata(13) <= \<const0>\;
  axi_out1_tdata(12) <= \<const0>\;
  axi_out1_tdata(11) <= \<const0>\;
  axi_out1_tdata(10) <= \<const0>\;
  axi_out1_tdata(9) <= \<const0>\;
  axi_out1_tdata(8) <= \<const0>\;
  axi_out1_tdata(7) <= \<const0>\;
  axi_out1_tdata(6) <= \<const0>\;
  axi_out1_tdata(5) <= \<const0>\;
  axi_out1_tdata(4) <= \<const0>\;
  axi_out1_tdata(3) <= \<const0>\;
  axi_out1_tdata(2) <= \<const0>\;
  axi_out1_tdata(1) <= \<const0>\;
  axi_out1_tdata(0) <= \<const0>\;
  axi_out1_tlast <= \<const0>\;
  axi_out1_tstrb(3) <= \<const0>\;
  axi_out1_tstrb(2) <= \<const0>\;
  axi_out1_tstrb(1) <= \<const0>\;
  axi_out1_tstrb(0) <= \<const0>\;
  axi_out1_tvalid <= \<const0>\;
  axi_out2_tdata(31) <= \<const0>\;
  axi_out2_tdata(30) <= \<const0>\;
  axi_out2_tdata(29) <= \<const0>\;
  axi_out2_tdata(28) <= \<const0>\;
  axi_out2_tdata(27) <= \<const0>\;
  axi_out2_tdata(26) <= \<const0>\;
  axi_out2_tdata(25) <= \<const0>\;
  axi_out2_tdata(24) <= \<const0>\;
  axi_out2_tdata(23) <= \<const0>\;
  axi_out2_tdata(22) <= \<const0>\;
  axi_out2_tdata(21) <= \<const0>\;
  axi_out2_tdata(20) <= \<const0>\;
  axi_out2_tdata(19) <= \<const0>\;
  axi_out2_tdata(18) <= \<const0>\;
  axi_out2_tdata(17) <= \<const0>\;
  axi_out2_tdata(16) <= \<const0>\;
  axi_out2_tdata(15) <= \<const0>\;
  axi_out2_tdata(14) <= \<const0>\;
  axi_out2_tdata(13) <= \<const0>\;
  axi_out2_tdata(12) <= \<const0>\;
  axi_out2_tdata(11) <= \<const0>\;
  axi_out2_tdata(10) <= \<const0>\;
  axi_out2_tdata(9) <= \<const0>\;
  axi_out2_tdata(8) <= \<const0>\;
  axi_out2_tdata(7) <= \<const0>\;
  axi_out2_tdata(6) <= \<const0>\;
  axi_out2_tdata(5) <= \<const0>\;
  axi_out2_tdata(4) <= \<const0>\;
  axi_out2_tdata(3) <= \<const0>\;
  axi_out2_tdata(2) <= \<const0>\;
  axi_out2_tdata(1) <= \<const0>\;
  axi_out2_tdata(0) <= \<const0>\;
  axi_out2_tlast <= \<const0>\;
  axi_out2_tstrb(3) <= \<const0>\;
  axi_out2_tstrb(2) <= \<const0>\;
  axi_out2_tstrb(1) <= \<const0>\;
  axi_out2_tstrb(0) <= \<const0>\;
  axi_out2_tvalid <= \<const0>\;
  axi_out3_tdata(31) <= \<const0>\;
  axi_out3_tdata(30) <= \<const0>\;
  axi_out3_tdata(29) <= \<const0>\;
  axi_out3_tdata(28) <= \<const0>\;
  axi_out3_tdata(27) <= \<const0>\;
  axi_out3_tdata(26) <= \<const0>\;
  axi_out3_tdata(25) <= \<const0>\;
  axi_out3_tdata(24) <= \<const0>\;
  axi_out3_tdata(23) <= \<const0>\;
  axi_out3_tdata(22) <= \<const0>\;
  axi_out3_tdata(21) <= \<const0>\;
  axi_out3_tdata(20) <= \<const0>\;
  axi_out3_tdata(19) <= \<const0>\;
  axi_out3_tdata(18) <= \<const0>\;
  axi_out3_tdata(17) <= \<const0>\;
  axi_out3_tdata(16) <= \<const0>\;
  axi_out3_tdata(15) <= \<const0>\;
  axi_out3_tdata(14) <= \<const0>\;
  axi_out3_tdata(13) <= \<const0>\;
  axi_out3_tdata(12) <= \<const0>\;
  axi_out3_tdata(11) <= \<const0>\;
  axi_out3_tdata(10) <= \<const0>\;
  axi_out3_tdata(9) <= \<const0>\;
  axi_out3_tdata(8) <= \<const0>\;
  axi_out3_tdata(7) <= \<const0>\;
  axi_out3_tdata(6) <= \<const0>\;
  axi_out3_tdata(5) <= \<const0>\;
  axi_out3_tdata(4) <= \<const0>\;
  axi_out3_tdata(3) <= \<const0>\;
  axi_out3_tdata(2) <= \<const0>\;
  axi_out3_tdata(1) <= \<const0>\;
  axi_out3_tdata(0) <= \<const0>\;
  axi_out3_tlast <= \<const0>\;
  axi_out3_tstrb(3) <= \<const0>\;
  axi_out3_tstrb(2) <= \<const0>\;
  axi_out3_tstrb(1) <= \<const0>\;
  axi_out3_tstrb(0) <= \<const0>\;
  axi_out3_tvalid <= \<const0>\;
GND: unisim.vcomponents.GND
     port map (
      G => \<const0>\
    );
end STRUCTURE;
