# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/erosc/Desktop/Vivado/MS2XS_01.xpr/MS2XS_01/MS2XS_01.srcs/sources_1/bd/BD/ip/BD_axi_dma_0_0/BD_axi_dma_0_0.xci
# IP: The module: 'BD_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/erosc/Desktop/Vivado/MS2XS_01.xpr/MS2XS_01/MS2XS_01.srcs/sources_1/bd/BD/ip/BD_axi_dma_0_0/BD_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'BD_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/erosc/Desktop/Vivado/MS2XS_01.xpr/MS2XS_01/MS2XS_01.srcs/sources_1/bd/BD/ip/BD_axi_dma_0_0/BD_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'BD_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/erosc/Desktop/Vivado/MS2XS_01.xpr/MS2XS_01/MS2XS_01.srcs/sources_1/bd/BD/ip/BD_axi_dma_0_0/BD_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BD_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/erosc/Desktop/Vivado/MS2XS_01.xpr/MS2XS_01/MS2XS_01.srcs/sources_1/bd/BD/ip/BD_axi_dma_0_0/BD_axi_dma_0_0.xci
# IP: The module: 'BD_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/erosc/Desktop/Vivado/MS2XS_01.xpr/MS2XS_01/MS2XS_01.srcs/sources_1/bd/BD/ip/BD_axi_dma_0_0/BD_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'BD_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/erosc/Desktop/Vivado/MS2XS_01.xpr/MS2XS_01/MS2XS_01.srcs/sources_1/bd/BD/ip/BD_axi_dma_0_0/BD_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'BD_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/erosc/Desktop/Vivado/MS2XS_01.xpr/MS2XS_01/MS2XS_01.srcs/sources_1/bd/BD/ip/BD_axi_dma_0_0/BD_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BD_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
