# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/erosc/Desktop/Vivado/NTRU_MS2XS/ms2sx_ip.xdc

# Block Designs: bd/BD/BD.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD || ORIG_REF_NAME==BD} -quiet] -quiet

# IP: bd/BD/ip/BD_processing_system7_0_0/BD_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_processing_system7_0_0 || ORIG_REF_NAME==BD_processing_system7_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_axi_dma_0_0/BD_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_axi_dma_0_0 || ORIG_REF_NAME==BD_axi_dma_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_ps7_0_axi_periph_0/BD_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_ps7_0_axi_periph_0 || ORIG_REF_NAME==BD_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/BD/ip/BD_rst_ps7_0_100M_0/BD_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_rst_ps7_0_100M_0 || ORIG_REF_NAME==BD_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/BD/ip/BD_axi_smc_0/BD_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_axi_smc_0 || ORIG_REF_NAME==BD_axi_smc_0} -quiet] -quiet

# IP: bd/BD/ip/BD_ms2xs_mult11bit_0_1/BD_ms2xs_mult11bit_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_ms2xs_mult11bit_0_1 || ORIG_REF_NAME==BD_ms2xs_mult11bit_0_1} -quiet] -quiet

# IP: bd/BD/ip/BD_ms2xs_0_0/BD_ms2xs_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_ms2xs_0_0 || ORIG_REF_NAME==BD_ms2xs_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_system_ila_0_0/BD_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_system_ila_0_0 || ORIG_REF_NAME==BD_system_ila_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_xbar_0/BD_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_xbar_0 || ORIG_REF_NAME==BD_xbar_0} -quiet] -quiet

# IP: bd/BD/ip/BD_axis_switch_0_0/BD_axis_switch_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_axis_switch_0_0 || ORIG_REF_NAME==BD_axis_switch_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_axis_switch_0_1/BD_axis_switch_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_axis_switch_0_1 || ORIG_REF_NAME==BD_axis_switch_0_1} -quiet] -quiet

# IP: bd/BD/ip/BD_auto_pc_0/BD_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_auto_pc_0 || ORIG_REF_NAME==BD_auto_pc_0} -quiet] -quiet

# XDC: bd/BD/BD_ooc.xdc
